import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, CheckCircle2, Clock3, Copy, Instagram, MessageCircle, ShieldCheck, Sparkles, Star, TrendingUp, Users, X, Zap } from "lucide-react";
import { trackEvent } from "@/lib/tracking";

const WHATSAPP_NUMBER = "5511999999999"; // substitua pelo número real
const PIX_KEY = "SUA-CHAVE-PIX-AQUI"; // substitua pela chave real
type Pack = { id:string; followers:string; label:string; price:number; description:string; popular?:boolean };
const packs:Pack[] = [
 {id:"start",followers:"500 seguidores",label:"Comece com presença",price:10,description:"Para dar o primeiro salto no perfil"},
 {id:"growth",followers:"1.000 seguidores",label:"Mais autoridade",price:15,description:"Ideal para perfis em crescimento"},
 {id:"pro",followers:"2.000 seguidores",label:"Perfil profissional",price:20,description:"Equilíbrio entre alcance e investimento",popular:true},
 {id:"scale",followers:"4.000 seguidores",label:"Escala máxima",price:35,description:"Para quem quer presença forte"}
];
const testimonials = [
 ["MC","Comerciante local","@feedback_real","Insira aqui um feedback real de cliente."],
 ["BL","Blogueira","@seu_cliente","Substitua por um depoimento autorizado."],
 ["PV","Prestador de serviço","@cliente_verificado","Use apenas resultados comprováveis."]
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function Index(){
 const [chosen,setChosen]=useState<Pack|null>(null),[left,setLeft]=useState(180),[copied,setCopied]=useState(false);
 useEffect(()=>{if(!chosen||left<=0)return;const id=window.setInterval(()=>setLeft(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(id)},[chosen,left]);
 const timer=useMemo(()=>String(Math.floor(left/60)).padStart(2,"0")+":"+String(left%60).padStart(2,"0"),[left]);
 const choose=(p:Pack)=>{setChosen(p);setLeft(180);setCopied(false);trackEvent("InitiateCheckout",{value:p.price,currency:"BRL",contentName:p.followers})};
 const send=()=>{if(!chosen)return;const msg="Olá! Quero confirmar meu pedido de seguidores reais.\n\nPacote: "+chosen.followers+"\nValor: "+money(chosen.price)+"\n\nVou anexar o comprovante do Pix nesta conversa.";trackEvent("Contact",{value:chosen.price,currency:"BRL",contentName:chosen.followers});window.open("https://wa.me/"+WHATSAPP_NUMBER+"?text="+encodeURIComponent(msg),"_blank","noopener,noreferrer")};
 return <div className="landing-page">
  <header className="site-header"><a className="brand" href="#inicio"><span className="brand-mark"><Instagram size={19}/></span>IMPULSO<span>SOCIAL</span></a><a className="header-link" href="#como-funciona">Como funciona <ArrowRight size={15}/></a></header>
  <main>
   <section className="hero section-shell" id="inicio"><div><div className="eyebrow"><Sparkles size={15}/> Presença que transmite confiança</div><h1>Seu perfil ainda parece pequeno para quem está pronto para comprar?</h1><p className="hero-subtitle">No Instagram, a primeira impressão pesa. Aumente o volume de <strong>seguidores reais</strong> e faça seu perfil transmitir mais autoridade, confiança e presença.</p><button className="primary-button" onClick={()=>document.getElementById("pacotes")?.scrollIntoView({behavior:"smooth"})}>Quero aumentar minha credibilidade agora <ArrowRight size={19}/></button><div className="micro-proof"><ShieldCheck size={17}/> Entrega rápida <span>•</span> Suporte pelo WhatsApp <span>•</span> Sem pedir senha</div></div><div className="hero-visual"><div className="glow glow-one"/><div className="glow glow-two"/><div className="phone-card"><div className="phone-top"><span>9:41</span><span>● ● ●</span></div><div className="profile-row"><div className="avatar-gradient"><Instagram/></div><div><strong>@seuperfil</strong><small>Perfil comercial</small></div><span className="verified">✓</span></div><div className="profile-stats"><span><b>2.480</b> seguidores</span><span><b>186</b> seguindo</span><span><b>94</b> posts</span></div><div className="profile-actions"><span>Seguir</span><span>Mensagem</span></div><div className="mini-posts"><i/><i/><i/><i/></div><div className="growth-pill"><TrendingUp size={17}/><span><b>+32%</b><small>mais percepção de autoridade</small></span></div></div></div></section>
   <section className="problem-section"><div className="section-shell"><div className="section-heading"><span className="section-kicker">O problema é percebido rápido</span><h2>Poucos seguidores podem fazer uma boa oferta parecer menos confiável.</h2><p>Antes de ler sua legenda, o cliente olha para o seu perfil e tira conclusões.</p></div><div className="problem-grid">{[["01","O cliente desconfia","Um perfil com pouco movimento pode gerar insegurança."],["02","Parece recém-criado","A falta de volume passa uma imagem de pouca experiência."],["03","A concorrência ganha espaço","O perfil mais estabelecido tende a conquistar atenção primeiro."]].map(x=><article className="problem-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
   <section className="benefits-section section-shell"><div className="section-heading"><span className="section-kicker">Mais presença no seu perfil</span><h2>Transforme o número de seguidores em uma primeira impressão mais forte.</h2></div><div className="benefits-grid">{[[Users,"Autoridade instantânea","Presença compatível com quem já atua no mercado."],[ShieldCheck,"Mais confiança do público","Reduza a sensação de risco na hora da compra."],[TrendingUp,"Efeito manada","Mais prova social ajuda novos visitantes a acompanhar."],[Zap,"Perfil estabelecido","Deixe seu Instagram mais pronto para vender."]].map(([I,t,d])=><article className="benefit-card" key={t as string}><div className="icon-box"><I size={22}/></div><h3>{t as string}</h3><p>{d as string}</p></article>)}</div><div className="real-followers-banner"><div className="banner-icon"><Check size={23}/></div><div><strong>Seguidores reais, não bots ou perfis falsos.</strong><p>Você não precisa entregar sua senha. Escolha o pacote e fale com o suporte.</p></div></div></section>
   <section className="social-section section-shell" id="depoimentos"><div className="section-heading"><span className="section-kicker">Prova social</span><h2>Quem aumenta a presença, comunica mais confiança.</h2><p>Troque os exemplos abaixo por feedbacks reais e autorizados antes de publicar.</p></div><div className="testimonial-grid">{testimonials.map(x=><article className="testimonial-card" key={x[2]}><div className="testimonial-top"><div className="client-avatar">{x[0]}</div><div><strong>{x[1]}</strong><small>{x[2]}</small></div><Star className="stars" size={16} fill="currentColor"/></div><p>“{x[3]}”</p><span className="verified-label"><CheckCircle2 size={14}/> Cliente verificado</span></article>)}</div></section>
   <section className="steps-section" id="como-funciona"><div className="section-shell"><div className="section-heading"><span className="section-kicker">Sem complicação</span><h2>Escolha, pague e envie seu pedido.</h2></div><div className="steps-grid">{[["01","Escolha seu pacote","Selecione a quantidade ideal."],["02","Pague via Pix","Copie a chave e pague pelo seu banco."],["03","Envie no WhatsApp","Envie comprovante e dados do perfil."]].map(x=><div className="step" key={x[0]}><span className="step-number">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</div></div></section>
   <section className="packages-section section-shell" id="pacotes"><div className="section-heading"><span className="section-kicker">Escolha seu impulso</span><h2>Comece com o pacote ideal para o seu objetivo.</h2><p>Pagamento único. Atendimento direto. Sem fidelidade.</p></div><div className="package-grid">{packs.map(p=><article className={"package-card "+(p.popular?"popular":"")} key={p.id}>{p.popular&&<div className="popular-badge">MAIS VENDIDO</div>}<div className="package-icon"><Instagram size={20}/></div><span className="package-label">{p.label}</span><h3>{p.followers}</h3><p>{p.description}</p><div className="package-price">{money(p.price)}</div><button className={"package-button "+(p.popular?"primary-button":"")} onClick={()=>choose(p)}>Escolher este pacote <ArrowRight size={17}/></button><small><Check size={13}/> Seguidores reais</small><small><Check size={13}/> Suporte via WhatsApp</small></article>)}</div></section>
  </main>
  <footer className="site-footer"><div className="section-shell footer-inner"><div className="brand"><span className="brand-mark"><Instagram size={19}/></span>IMPULSO<span>SOCIAL</span></div><div className="footer-trust"><span><Zap size={16}/> Entrega rápida</span><span><MessageCircle size={16}/> Suporte via WhatsApp</span><span><Users size={16}/> Seguidores reais</span></div><p>© 2026 Impulso Social. Instagram é uma marca da Meta Platforms, Inc.</p></div></footer>
  {chosen&&<div className="modal-backdrop" onClick={()=>setChosen(null)}><div className="payment-modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="close-button" onClick={()=>setChosen(null)} aria-label="Fechar"><X size={20}/></button><div className="modal-icon"><Copy size={23}/></div><span className="section-kicker">Seu pedido</span><h2>{chosen.followers}</h2><div className="modal-price">{money(chosen.price)}</div><div className="pix-box"><div><small>Chave Pix — copiar e colar</small><strong>{PIX_KEY}</strong></div><button onClick={async()=>{await navigator.clipboard?.writeText(PIX_KEY);setCopied(true)}} aria-label="Copiar chave Pix">{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><p className="payment-instruction">Após realizar o pagamento, aguarde a confirmação automática. Isso leva alguns instantes.</p><div className={"confirmation-timer "+(left===0?"done":"")}><Clock3 size={18}/>{left===0?"Pagamento pronto para confirmação":"Confirmando seu pagamento... "+timer}</div><button className="primary-button whatsapp-button" disabled={left>0} onClick={send}><MessageCircle size={19}/> Enviar pedido no WhatsApp</button>{left>0&&<small className="wait-note">O botão será liberado ao final da confirmação.</small>}</div></div>}
 </div>;
}